
language: node_js
node_js:
  - stable
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

before_script:
  - npm install -g @angular/cli

script:
#  - ng build ng-joystick --prod
#  - ng test ng-joystick --browsers ChromeHeadlessNoSandbox --watch false
  - npm run build-library
  - npm run test-lib-headless
  - npm run test-app-headless-coverage
  - npm run coverage

# after_success: npm run coverage
